apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: node-local-dns
  namespace: kube-system
spec:
  interval: 24h
  path: "cluster/addons/dns/nodelocaldns"
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubernetes
